# Generated by Django 2.2.8 on 2020-01-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('item_type', models.CharField(max_length=50)),
                ('sales_channel', models.BooleanField(default=False)),
                ('order_priority', models.CharField(max_length=2)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('order_id', models.PositiveIntegerField(blank=True, null=True)),
                ('ship_date', models.DateField(blank=True, null=True)),
                ('units_sold', models.PositiveIntegerField(blank=True, null=True)),
                ('unit_price', models.FloatField(blank=True, null=True)),
                ('unit_cost', models.FloatField(blank=True, null=True)),
                ('total_revenue', models.FloatField(blank=True, null=True)),
                ('total_cost', models.FloatField(blank=True, null=True)),
                ('total_profit', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
