# Generated by Django 2.2.8 on 2020-01-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_pizzas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='image',
            field=models.ImageField(blank=True, height_field=230, null=True, upload_to='pizzas', width_field=230),
        ),
    ]
