# Generated by Django 2.2.8 on 2020-01-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191216_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='d490efc750664ebf97fd12932313ab5c208e49effa3f431bad1e45be5b6f4402', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='a93b1ff480574a5894266edfb1d5f93761be607c65fa40d8a7cc6184920850ca', max_length=300, null=True),
        ),
    ]
