# Generated by Django 2.2.8 on 2020-01-20 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warrior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(choices=[('strong', 'Strong'), ('healthy', 'Healthy'), ('skill', 'Skill')], max_length=10)),
                ('power', models.FloatField(default=10)),
                ('health', models.FloatField(default=100)),
                ('skill', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('warrior_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fight.Warrior')),
                ('kick', models.CharField(choices=[('head', 'head'), ('body', 'body'), ('foot', 'foot')], max_length=10)),
                ('block', models.CharField(choices=[('head', 'head'), ('body', 'body'), ('foot', 'foot')], max_length=10)),
            ],
            bases=('fight.warrior',),
        ),
    ]
