# Generated by Django 2.2.8 on 2020-01-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight',
            name='block',
            field=models.CharField(choices=[('head', 'head'), ('body', 'body'), ('foot', 'foot')], max_length=10),
        ),
        migrations.AlterField(
            model_name='fight',
            name='kick',
            field=models.CharField(choices=[('head', 'head'), ('body', 'body'), ('foot', 'foot')], max_length=10),
        ),
    ]
